before_script:
  - cd $CI_PROJECT_DIR
  - pip install --upgrade pip
  - pip install -r requirements

stages:
  - test

unit-test-job:
  stage: test
  script:
    - echo "testing"
    - python -m pytest