before_script:
  - cd $CI_PROJECT_DIR
  - pip install --upgrade pip
  - pip install -r requirements

stages:
  - test
  - deploy

unit-test-job:
  stage: test
  script:
    - echo "testing"
    - python -m pytest

deploy-job:
  stage: deploy
  script:
    - echo "deploying"
    - cd app
    - timeout 10s python -m flask run
